spring.application.name=backend
server.port = 8082
spring.datasource.url=jdbc:postgresql://localhost:5432/absolutecinema

spring.datasource.username=postgres
spring.datasource.password=anand123
spring.security.user.name=tony
spring.security.user.password=tony123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anandkumar001k@gmail.com
spring.mail.password=ehkeykxvmexklhbg

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true